Add unit tests for com.analysys.presto.connector.hbase.utils.Utils
Diffblue-benchmarks/analysys-presto-hbase-connector pull request #1
Opened 2019-05-23 13:58 UTC by ThomasPerkins1123

Hi,

I've analysed your code base and noticed that `com.analysys.presto.connector.hbase.utils.Utils` in the `presto0.20-hbase` module is not fully tested.

I've written some tests that cover this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.

2019-05-23 18:03 UTC, freddytuxworth requested changes

2019-05-23 18:03 UTC, freddytuxworth commented on src/test/java/com/analysys/presto/connector/hbase/utils/UtilsTest.java
> +  public void testIsBatchReturnFalse() {
test name is missing `Get`

2019-05-23 18:03 UTC, freddytuxworth commented on src/test/java/com/analysys/presto/connector/hbase/utils/UtilsTest.java
> +  public void testIsBatchReturnTrue() {
test name is missing `Get`

2019-05-24 08:50 UTC, freddytuxworth approved these changes

2019-05-24 12:50 UTC, paulkennethkent approved these changes

2019-07-24 15:03 UTC, merged